vippsas/vipps-ecom-api

- docs/swagger.yaml
Added missing spaces in line 149, 230,
> Aded missing spaces to  swagger.yaml line 149 and 230

- vipps-ecom-api.md
New error message for error code 62: The amount you tried to capture is not reserved
> Updated error message for error code 62

- docs/ecom.html
- docs/swagger.json
- docs/swagger.yaml
- vipps-ecom-api.md
Fixes issues related to #60 and #52
> Fixes to definitions of postCodes

- docs/swagger.json
- docs/swagger.yaml
- vipps-ecom-api.md
Updated gthe example URLs:
* callback: https://example.com/vipps/callbacks-for-payment-update
* fallback: https://example.com/vipps/fallback-success-page/order123abc
> Clarification: Callback + fallback

- docs/swagger.yaml
* Merged as in https://github.com/vippsas/vipps-ecom-api/issues/116
* Removed a few "DTO" suffixes
* Removed "get" from some schemas
* Minor improvements for less WTFs
> Merging and tweaking

- vipps-ecom-api-faq.md
Planned to divide the ToC, but gave up.
> FAQ toc split

- tools/vipps-ecom-api-postman-collection.json
- Added Vipps-System headers (only Vipps-System-Name and Vipps-System-Verison are on by default)
- Added Merchant-Serial-Number header
- Added two collection variables, {{vipps_system_name}} and {{collection_version}}, collection_version is using the current date for versoning.
- Changed order of headers to be more consistent between requests
> Added optional system & msn headers

- docs/swagger.yaml
- vipps-ecom-api.md
Ruter reported that we returned 'PAYMENTS' when our documentation says 'PAYMENT'.
Mr. TT confirmed no changes has been made.
> changed error group 'Payment' to 'Payments'

- vipps-ecom-api-faq.md
Updated text with details as to why this is the way it is.
> Added more details "vipps-nummer"

- vipps-ecom-api-faq.md
Grouping of questions, with section headings. ToC also updated.
> FAQ: Restructure, sections in ToC

- vipps-ecom-api-faq.md
https://vippsas.slack.com/archives/C01BQJTPD09/p1613135939072600
> Multiple sale units

- docs/swagger.yaml
- vipps-ecom-api-faq.md
WIP.
See: https://github.com/vippsas/vipps-ecom-api/issues/183
> Azure: unauthorized_client

- tools/vipps-ecom-api-postman-collection.json
Added QR code requests (URL and PNG) to Collection
Added tests to collect `vippsLandingPageURL` for use with QR
> Added QR code requests to Postman Collection

- vipps-ecom-api-faq.md
- vipps-ecom-api.md
Draft.
Slack: https://vippsas.slack.com/archives/C8HP1AJ79/p1639506363233700
> PSP vs eCom: Soft-decline

- vipps-ecom-api.md
Work in progress! See Slack: https://vippsas.slack.com/archives/C01BQJTPD09/p1651043080264309
> Recommendations for handling peak traffic

- vipps-ecom-api.md
Using isApp comes with some additional responsibility.
> isApp clarification

- docs/shins/index.html
- tools/vipps-ecom-api-postman-collection.json
- tools/vipps-ecom-api-postman-environment.json
Update ecom collection and environment to include vipps headers:
- Merchant-Serial-Number
- Vipps-System-Name 
- Vipps-System-Version
- Vipps-System-Plugin-Name
- Vipps-System-Plugin-Version
> Update ecom collection and environment example to include more headers

- docs/swagger.yaml
- Changed `ErrorObject` to `ErrorFromAzure` to make it clear that this is an error from Microsoft Azure.
- Changed `Default` to `ErrorResponse`.
- Added some description and details about the errors.
- Examples and tweaks.
> Error clean-up

- vipps-ecom-api-faq.md
- vipps-ecom-api.md
Based on Slack discussion: https://vippsas.slack.com/archives/CE3SU3YDN/p1655302126793869
> Clarified: Release remaining funds

- vipps-ecom-api.md
Slack: https://vippsas.slack.com/archives/C02ARD76KD1/p1660563247913169
> transactionText recommendations

- vipps-ecom-api.md
Even more details for errorCode 81, unknown user.
> Foreign numbers

- vipps-ecom-postman.md
Replace the links from raw content to relative links to ease transition to docusaurus
> Replace the links from raw content to relative links

- vipps-ecom-api-faq.md
> Revert commit d0e4ca569cd4bcd27aff4fae7b25f83cf4a4c03a

- README.md
> Link to redoc in new website

- vipps-ecom-api-quick-start.md
Just as an example. Based on the "call-by-call" section in the API guide. Can be extended a bit with some more links to the main API guide, FAQ, etc.
> Quick start guide: Initial version

- docs/swagger.yaml
TicketNumber should be marked as optional, as it indeed is optional :)
> Make additionalData.ticketNumber optional

- vipps-ecom-api.md
https://vippsas.slack.com/archives/CD9AJD2F5/p1675335360278879
> Remove note. This warning is no longer valid.

- vipps-ecom-api.md
Update links to new section and remove duplicated material.
> Streamline userinfo in ecom api guide

- README.md
- vipps-ecom-api.md
Similar to https://github.com/vippsas/vipps-epayment-api/pull/145
> Use the ePayment API

- vipps-ecom-api.md
Required to avoid when doing new changes to the docusaurus build
> CI-2189: Link to markdown files

- vipps-ecom-api-checklist.md
- vipps-ecom-api-quick-start.md
Fixes a download issue on developer.vippsmobilepay.com
> CI-2251: Make links to downloadable files absolute

- docs/swagger.yaml
Matches https://github.com/vippsas/vipps-epayment-api/pull/175
> Phone number, manual POS
